services:
  frontend:
    build:
      context: .
    ports:
      - "${PORT:-5173}:5173"
    depends_on:
      - server
      - spawner
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - VITE_BACKEND_BASE_URL=${BACKEND_URL}
      - VITE_WEBSOCKET_BASE_URL=${WEBSOCKET_URL}
      - VITE_WEBSOCKET_URL=${WS_URL}
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}

  server:
    build:
      context: ../server
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: "npm run dev"

  spawner:
    build:
      context: ../spawner
    ports:
      - "${SPAWNER_PORT:-3000}:3000"