services:
  frontend:

    build:
      context: .
    ports:
      - "${PORT:-5173}:5173"
    depends_on:
      - server
      - spawner


  server:

    build:
      context: ../server
    ports:
      - "${SERVER_PORT:-8080}:8080"

    command: "npm run dev"

  spawner:
    build:
      context: ../spawner
    ports:
      - "${SPAWNER_PORT:-3000}:3000"