

services:
  prisma:
    image: postgres:15
    container_name: prisma_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prisma_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  lb:
    image:  haproxy
    ports:
      - "5173:5173"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  streamserver1:
    image: streamserver
    environment:
      - APPID=1111
  streamserver2:
    image: streamserver
    environment:
      - APPID=2222
  streamserver3:
    image: streamserver
    environment:
      - APPID=3333
  streamserver4:
    image: streamserver
    environment:
      - APPID=4444

volumes:
  postgres_data: